[package]
name = "hinode-efi"
version = "0.1.0"
edition = "2021"
description = "A generic Rust-based UEFI project for AArch64 systems."
publish = false

[[bin]]
name = "hinode"
path = "src/main.rs"

[dependencies]
log = "0.4"
uefi = { version = "0.38", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
uefi-raw = "0.14"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = true
